[theme]
primaryColor="#C9E8F0"
backgroundColor="#7FC9DC"
secondaryBackgroundColor="#EBF7FA"
textColor="#0D0910"
font = "Verdana"
codeFont = "JetBrains Mono:https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap"
