[theme]
primaryColor="#F5FBFF"
backgroundColor="#EDFBFF"
secondaryBackgroundColor="#0081D7"
textColor="#0003848"
font = "Verdana"
codeFont = "JetBrains Mono:https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap"
